### ISSUE TITLE
Prevent begining of new round if sync didn't complete successfully

### ISSUE THREAD

**Issue by tvand7093** [BMVW-Capstone/Mobile-Rounds#99]
The app will currently write out an empty file essentially upon any failure. We should ensure that the sync was a success before letting the user continue working.

edit:  this is referring to the serialized local files wiping if an error occurs during certain transactions

**Comment by ChrisWillette** [comment]
~~Gonna do this essentially the same way that I implemented the TestConnection method in #120~~ nothing in life or UWP is simple.

**Comment by ChrisWillette** [comment]
what do the put/post commands of `IApiRequest` return on success or failure?
```
var completedRound = await request.PostAsync<RoundModel>(
                    Constants.Endpoints.Rounds, CurrentRound);

            if(completedRound?.Id != Guid.Empty)
            {
             //TODO: Modify the logic here to NOT complete the round if we could not delete
             //the file.
```
**gonna do some things in here based on the return codes from completedRound**

```
                //means the upload was a success, so continue with the deletion of the round.
                if(await DeleteCurrentRoundAsync())
                {
                    return completedRound;
                }
            }
```
but I'd like to make sure I'm right, first.

**Comment by ChrisWillette** [comment]
in screwing with this, i noticed a related bug. if a user tries to sync with the server when it can't be contacted, the whole app will crash (tested by killing my server after starting the round but before syncing). It seems like wrapping calls to `IApiRequest request = ServiceResolver.Resolve<IApiRequest>();` with an error check can resolve this issue on both fronts (along with raising some kind of canProgress flag for UI sake). I'm thinking that we can just use a HEAD call and check what the server sends back, but since I know little about `IApiRequest` I'm gonna have to shelve this for now.
